### ISSUE TITLE
Extend some ESLint configuration

### ISSUE THREAD

**Issue by JingYenLoh** [francisyzy/TODO.node#1]
Setup your ESLint so that it runs properly in VSCode

Here's [an article](https://travishorn.com/setting-up-eslint-on-vs-code-with-airbnb-javascript-style-guide-6eb78a535ba6) that might help, I briefly looked through it and it's probably ok

Some steps can be skipped of course

I would simply save all the ESLint packages as development dependencies though (using `npm i -D` instead of `npm i -S`)

**Comment by francisyzy** [comment]
Was thinking of using [standard](https://github.com/standard/standard) I am not sure if I am comfortable with the inflexibility of it. I will try [eslint-config-standard](https://github.com/standard/eslint-config-standard) and report back.

Thanks for letting me know theres a development dependency option available!
